resolver: lts-17.5
packages:
- .
- examples/central-counter

extra-deps:
- servant-subscriber-0.7.0.0
- git: https://github.com/shmish111/purescript-bridge.git
  commit: fb8a038e4c9a97377834779ec6b2e0e7faf5b2a1

nix:
  enable: true
  packages:
    - zlib
  path: [nixpkgs=/home/juan/tweag/zeuslogics/nix]
